### ISSUE TITLE
New Error After Updating Some Custom Nodes

### ISSUE THREAD

**Issue by charliebrown777** [Satellile/yara#4]
Sorry to bother you again, but I am getting errors as follows after I updated some custom nodes:
Error message in Yara:
![image](https://github.com/Satellile/yara/assets/36913431/2c25d894-e6a1-41c7-9753-09a141f10f06)

Error message in ComfyUi
![image](https://github.com/Satellile/yara/assets/36913431/e110963b-19e0-4710-87e2-8d6fd82883ae)

I put the original PNG into the UI and it can generate the images properly but not with yara regen.

Thank you!

**Comment by charliebrown777** [comment]
I also used updated settings to generate a new pic, and got the same error in return.

**Comment by charliebrown777** [comment]
I see the problem comes from other nodes after upgrading. I just solved it with the help of Claude... Thank you!

**Comment by Satellile** [comment]
Oop, sorry about the lack of response. Glad you were able to solve it!

**Comment by charliebrown777** [comment]
> Oop, sorry about the lack of response. Glad you were able to solve it!

It's OK. I found your tool very useful. Just keep updating it. I will let you know if I have any problems. Thank you again.
