### ISSUE TITLE
Unable to use yara if you set a different port for comfyui

### ISSUE THREAD

**Issue by Yaiol** [Satellile/yara#5]
Apparently the port to query comfui 8188 is defined as a constant in the program

Although ComfyUi can be launched on a custom port 
python.exe -s main.py --windows-standalone-build --port 7804

Both Address and port should be configurable

**Comment by Satellile** [comment]
Thanks for the issue! I was originally thinking of having this be customizable, but I was using the default port and hosting locally, and figured most people were doing the same, so I didn't add it in.

I just quickly added the functionality and bumped the version to [Yara v1.0.3](https://github.com/Satellile/yara/releases/tag/v1.0.3). I'm spending time working on other projects and playing games, so I didn't test it. If you use it, please let me know if any issues/bugs arise
